---
- name: Set Certbot script variable.
  set_fact:
    certbot_script: "{{ certbot_dir }}/certbot-auto"

- import_tasks: 'install-from-source-git.yml'
  when: certbot_install_from_source_method == 'git'

- import_tasks: 'install-from-source-url.yml'
  when: certbot_install_from_source_method == 'url'

- name: Ensure certbot-auto is executable.
  file:
    path: "{{ certbot_script }}"
    mode: 0755
